name: Update user secrets
on:
  push:
    branches: main
    paths: .github/workflows/update-user-secrets.yml
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  update-user-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: jcbhmr/set-secrets-action@v1
        with:
          token: ${{ secrets.USER_SECRETS_TOKEN }}
          repositories: |
            jcbhmr/md-html
            jcbhmr/node-45981
            jcbhmr/html-simple-dialogs
          secrets: |
            NPM_TOKEN=${{ secrets.NPM_TOKEN }}
